server:
  port: 8084

spring:
  application:
    name: API-GATEWAY

  cloud:
    .gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotel/**

        - id: USER-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/rating/**



eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#okta configuration for api gateway

okta:
  oauth2:
    issuer: https://dev-14717452.okta.com/oauth2/default
    audience: api://default
    client-id: 0oa9o5jlfyYSMcNFc5d7
    client-secret: cNuP4jZZ67xDrVRCblrkRnsjX3cMFT5i1IW-pgrd
    scopes: openid, profile, email, offline_access